CREATE DATABASE IF NOT EXISTS proje 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_general_ci;


USE proje;

CREATE TABLE IF NOT EXISTS Kullanicilar(
	KullaniciID INT AUTO_INCREMENT PRIMARY KEY,
	KullaniciAdi VARCHAR(50) UNIQUE NOT NULL,
	SifreHash VARCHAR(255) NOT NULL,
	AdSoyad VARCHAR(100) NOT NULL,
	Eposta VARCHAR(100) NOT NULL UNIQUE,
	ROL ENUM ('Ogretmen', 'Ogrenci') NOT NULL
	
);

CREATE TABLE IF NOT EXISTS Dersler(
	DersID INT AUTO_INCREMENT PRIMARY KEY,
	DersKodu VARCHAR(10) UNIQUE NOT NULL,
	DersAdi VARCHAR(120) NOT NULL,
	DersOgretmenID INT NOT NULL,
	
	FOREIGN KEY (DersOgretmenID) REFERENCES Kullanicilar(KullaniciID)
		ON DELETE RESTRICT
		ON UPDATE CASCADE
	
);

CREATE TABLE IF NOT EXISTS OgrenciDersKayitlari(
	KayitID INT AUTO_INCREMENT PRIMARY KEY,
	OgrenciID INT NOT NULL,
	DersID INT NOT NULL,
	
	CONSTRAINT ogrenci_ders UNIQUE (OgrenciID, DersID),
	
	FOREIGN KEY (OgrenciID) REFERENCES Kullanicilar(KullaniciID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
		
	FOREIGN KEY (DersID) REFERENCES Dersler(DersID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	
);

CREATE TABLE IF NOT EXISTS Sinavlar(
	SinavID INT AUTO_INCREMENT PRIMARY KEY,
	DersID INT NOT NULL,
	Baslik VARCHAR(150) NOT NULL,
	Aciklama TEXT NULL,
	SureDakika INT NOT NULL,
	OlusturmaTarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	
	FOREIGN KEY (DersID) REFERENCES Dersler(DersID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	
);

CREATE TABLE IF NOT EXISTS Sorular(
	SoruID INT AUTO_INCREMENT PRIMARY KEY,
	SinavID INT NOT NULL,
	SoruMetni TEXT NOT NULL,
	SoruTipi ENUM ('CoktanSecmeli', 'DogruYanlis') NOT NULL,
	
	
	FOREIGN KEY (SinavID) REFERENCES Sinavlar(SinavID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	
);

CREATE TABLE IF NOT EXISTS Secenekler(
	SecenekID INT AUTO_INCREMENT PRIMARY KEY,
	SoruID INT NOT NULL,
	SecenekMetni VARCHAR(255) NOT NULL,
	DogruMu BOOLEAN NOT NULL DEFAULT FALSE,
	
	
	FOREIGN KEY (SoruID) REFERENCES Sorular(SoruID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	
);


CREATE TABLE IF NOT EXISTS OgrenciSinavSonuclari(
	SonucID INT AUTO_INCREMENT PRIMARY KEY,
	SinavID INT NOT NULL,
	OgrenciID INT NOT NULL,
	Puan DECIMAL(5, 2) NOT NULL,
	BitisZamani TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	
	CONSTRAINT ogrenci_sinav UNIQUE (OgrenciID, SinavID),
	
	
	FOREIGN KEY (SinavID) REFERENCES Sinavlar(SinavID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	
	FOREIGN KEY (OgrenciID) REFERENCES Kullanicilar(KullaniciID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	
);



